name: code-quality

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Run spotless check
        run: |
          mvn -v
          mvn spotless:check
