# Diagrams from https://githubnext.com/projects/repo-visualization/

name: create-diagram

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Create diagram

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Repo Visualizer
        uses: githubocto/repo-visualizer@0.9.1
